# Generated by Django 6.0.2 on 2026-08-20 09:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "location_type",
                    models.CharField(
                        choices=[("warehouse", "Warehouse"), ("store", "Store")],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="pos.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0"), max_digits=18
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Stock In"),
                            ("OUT", "Stock Out"),
                            ("TRANSFER", "Transfer"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RESERVE", "Reserve"),
                            ("RELEASE", "Release"),
                            ("DAMAGE", "Damage"),
                            ("EXPIRE", "Expire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=6, max_digits=18)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="pos.product",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_movements",
                        to="pos.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Example: Carton, Roll, Sachet, Truck, Gallon, Keg",
                        max_length=100,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        blank=True,
                        help_text="Example: ctn, roll, kg, gal",
                        max_length=30,
                    ),
                ),
                (
                    "conversion_to_base",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("is_base_unit", models.BooleanField(default=False)),
                ("is_sellable", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="pos.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sale_items",
                to="pos.productunit",
            ),
        ),
        migrations.CreateModel(
            name="ProductUnitPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "allow_below_cost",
                    models.BooleanField(
                        default=False,
                        help_text="Allow selling below cost as an incentive/reward.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing",
                        to="pos.productunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("DAMAGED", "Damaged"),
                            ("EXPIRED", "Expired"),
                            ("IN_TRANSIT", "In Transit"),
                            ("QUARANTINED", "Quarantined"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balances",
                        to="pos.product",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="pos.location",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "location", "status"),
                        name="unique_product_location_status",
                    )
                ],
            },
        ),
    ]
