# Generated by Django 6.0.2 on 2026-03-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_customer_rename_sold_by_sale_cashier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
