# Generated by Django 6.0.2 on 2026-09-19 19:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_product_recognition_enabled_productimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
    ]
