# Generated by Django 6.0.2 on 2026-08-20 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylog",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pos.product"
            ),
        ),
    ]
