# Generated by Django 6.0.2 on 2026-03-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                ],
                max_length=10,
            ),
        ),
    ]
